{% set version = "0.1.8" %}

package:
  name: pycentroids
  version: {{ version }}

source:
  git_url: https://github.com/NSLS-II/centroids
  git_rev: v{{ version }}

build:
  number: 0
  script: python setup.py install

requirements:
  host:
    - python
    - pip

  build:
    - setuptools
    - cmake
    - gxx_linux-64
    - cpplint
    - pybind11

  run:
    - python
    - numpy
    - scipy
    - pandas
    - lmfit-c

test:
  requires:
    - pytest
    - pytest-runner
  imports:
    - pycentroids
  commands:
    - pytest --pyargs pycentroids.tests

about:
  home: https://github.com/NSLS-II/centroids
  license: BSD 3-clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stuwilkins
