{% set version = "0.1.8" %}

package:
  name: pycentroids
  version: {{ version }}

source:
  git_url: https://github.com/NSLS-II/centroids
  git_rev: v{{ version }}

build:
  number: 0
  script: python setup.py install

requirements:
  host:
    - python
    - pip
    - setuptools
  build:
    - setuptools
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cpplint
    - lmfit-c
    - pybind11
  run:
    - python
    - lmfit-c
    - pandas
    - scipy
    - {{ pin_compatible('numpy')  }}

test:
  requires:
    - pytest
  imports:
    - pycentroids
  commands:
    - pytest --pyargs pycentroids.tests

about:
  home: https://github.com/NSLS-II/centroids
  license: BSD 3-clause
  license_file: LICENSE

