{% set name = "pycentroids" %}
{% set version = "0.1.12" %}
{% set sha256 = "a6009f50b442bb047e266195e1cfa7c84a0d01760781669f71d449a4bdbc595c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: true  # [win]

requirements:
  host:
    - python
    - pip
    - pytest-runner
  build:
    - python
    - pip
    - cmake
    - cpplint
    - pybind11
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - python
    - pandas
    - scipy
    - {{ pin_compatible('numpy')  }}

test:
  requires:
    - pytest
  imports:
    - pycentroids
  commands:
    - pytest --pyargs pycentroids.tests

about:
  home: https://github.com/NSLS-II/centroids
  license: BSD 3-clause
  license_file: LICENSE
