{% set name = "pycentroids" %}
{% set version = "0.2.0rc2" %}
{% set sha256 = "642109bffe3c2733c06e897b91bc999ea0e960981fea8ba74ddce25e90faf5fe" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: true  # [win]

requirements:
  host:
    - python
    - pip
    - pytest-runner
  build:
    - python
    - pip
    - cmake
    - cpplint
    - numpy
    - pybind11
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - python
    - pandas
    - scipy
    - {{ pin_compatible('numpy')  }}

test:
  requires:
    - pytest
  imports:
    - pycentroids
  commands:
    - pytest --pyargs pycentroids.tests

about:
  home: https://github.com/NSLS-II/centroids
  license: BSD 3-clause
  license_file: LICENSE/LICENSE
