{% set name = "pycentroids" %}
{% set version = "0.1.9" %}
{% set sha256 = "cfc37c7ce62e2ea231c93af1a8a227c5b2fc18b5a7e95cfc4be07857fd904502" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NSLS-II/centroids/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  build:
    - python
    - pip
    - cmake
    - cpplint
    - pybind11
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - python
    - pandas
    - scipy
    - {{ pin_compatible('numpy')  }}

test:
  requires:
    - pytest
  imports:
    - pycentroids
  commands:
    - pytest --pyargs pycentroids.tests

about:
  home: https://github.com/NSLS-II/centroids
  license: BSD 3-clause
  license_file: LICENSE
