{% set name = "pycentroids" %}
{% set version = "0.1.8" %}
{% set sha256 = "345868be12c735681d22f3d2934af6c52c49f1cd27e2465b3e46df29daac8477" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NSLS-II/centroids/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - pytest-runner
  build:
    - cmake
    - cpplint
    - lmfit-c
    - pybind11
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - python
    - lmfit-c
    - pandas
    - scipy
    - {{ pin_compatible('numpy')  }}

test:
  requires:
    - pytest
  imports:
    - pycentroids
  commands:
    - pytest --pyargs pycentroids.tests

about:
  home: https://github.com/NSLS-II/centroids
  license: BSD 3-clause
  license_file: LICENSE
